### ISSUE TITLE
Missing fixes from 3.1.2 in 3.3.x

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#34]
There was a significant commit that made up 3.1.2 that has not been merged back onto `master` and thereby not `develop`:

https://github.com/jeffwils/grails-spring-security-saml/commit/60ab68fe3a8d1f9c74ee1d3de6da53758f53ab0b

Do we still need this fix?

If yes, we need to merge and test.

**Comment by valentingoebel** [comment]
If I have understood the fix correctly it allows you to specify a list of "role->saml group" maps, rather than a single "role->saml group" map.

3.1.2
```
userGroupToRoleMapping:
    - ROLE_MEMBER: member
    - ROLE_MEMBER: admin
```

current
```
userGroupToRoleMapping:
    ROLE_MEMBER: member
    ROLE_MEMBER: admin # not possible
```

The problem with the single map approach is that it's only possible to assign a role to a single group.

If we're going to break backwards compatibility wouldn't it be far more intuitive to have a single map that does "saml group -> list of roles"? After all the name of the property is "userGroupToRoleMapping" but for some reason the current version does the opposite namely "roleToUserGroupMapping".

new
```
userGroupToRoleMapping:
    member:
        - ROLE_MEMBER
    admin:
        - ROLE_MEMBER
```

Alternatively we could also support a mapping from saml groups to [spring security core groups](https://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html#authorityGroupClass).

**Comment by valentingoebel** [comment]
There is also a minor change at the bottom of the commit. We definitively need this change.

```
defaultFailureUrl = conf.saml.loginFailUrl ?: '/login/authfail?login_error=1'
```

**Comment by valentingoebel** [comment]
The default value of autoCreate.key is defined in plugin.yml as "username" and this is sufficient as a replacement.

autoCreate.assignAuthorities is true by default but it is only used in SpringSamlUserDetailsService where it is guarded by if(autoCreate.active).

We don't need to add those lines of code to the latest version.

**Comment by irstevenson** [comment]
Basic items have been addressed, the remaining item of Group to Role mapping has now been detailed and split over into #41.

**Comment by valentingoebel** [comment]
The behavior of defaultIDP no longer matches the README.MD file. The EntityID of the IDP has to be entered rather than the name that was specified in the `providers` block.

**Comment by irstevenson** [comment]
Yeah, that seemed to come from no where suddenly. That was the item I mentioned in matrix a few weeks back where one day all was working fine, and then suddenly the next I had to rework my `providers` block - I didn't realise it was only the `defaultIdp`, so I also changed the provider key.

I'm not sure what triggered this though... I wonder if some underlying dependency changed. :confused: But I don't think it was specific to new code in 3.3.x - because at one stage all was fine with 3.3.x. :confused: 

Should we set up a new issue for this? And/or, do you have more info?

**Comment by valentingoebel** [comment]
It's probably caused by your [last commit](https://github.com/jeffwils/grails-spring-security-saml/commit/16a9cb683f3e8538e918b33d9d86cc61bedb4b92) which re-enabled the defaultIDP setting. I feel like the new behavior is correct though. A metadata file defined in the providers section could in theory contain more than one service provider.

**Comment by irstevenson** [comment]
Ahhh, gotcha. I see now, man I was so stressed at the time with to many things happening at once I missed the simple thing.

Alright, so all that makes sense and yes we should just update the doco - but we'll want to wait until #46 is merged - however it looks like we also need to update the example blocks in the doco too (not just the table). I'll create a ticket so that's clear. ;)

Mind you, there's probably a bit that needs to be done on the doco, so that'll be worthwhile either-way.
