### ISSUE TITLE
Split README.md into README.md and USAGE.md

### ISSUE THREAD

**Issue by irstevenson** [jeffwils/grails-spring-security-saml#42]
Due to the way that plugins.grails.org displays the `README.md` on a the main page of the plugin (see http://plugins.grails.org/plugin/jeffwils/spring-security-saml), we need to be careful what's in `README.md`. For example, the table of configuration properties in the current `README.md` does not render on plugins.grails.org - and as a result, makes the quality of the plugin look questionable.

As a result, I believe it'd be best to split `README.md` at the 'Configuration' heading, and place everything from there down in a new `USAGE.md`. Then, have a link in `README.md` to `USAGE.md`. (I believe that link will then also be accessible from plugins.grails.org.)

This is similar to what I see other plugins doing - although if you look at Spring Security Core plugin, they're a bit more sever.

**Comment by valentingoebel** [comment]
We have an [official project site](https://jeffwils.github.io/grails-spring-security-saml/) where we should put the extended documentation. If you click on the "Documentation" link on the plugin site you will get redirected to that page. The big question is how do we modify that project site. I'm pretty sure that it's just show the current README.MD.

How do we split it so that github shows the full docs but the grails plugin site only shows the readme?

**Comment by valentingoebel** [comment]
@jeffwils Do you know how we can modify the project site?

**Comment by valentingoebel** [comment]
For reference: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

**Comment by valentingoebel** [comment]
https://github.com/jeffwils/grails-spring-security-saml/pull/46 has solved this issue.
