### ISSUE TITLE
Correct Configuration for URLs

### ISSUE THREAD

**Issue by HybridProgrammer** [jeffwils/grails-spring-security-saml#6]
What are the correct URLs for IDP AssertionConsumerService? Specifically HTTP-POST, HTTP-Artifact and PAOS?

I've tried using the following format: 
/saml/SSO/alias/mysp

However after login I am redirected to defaultFailureUrl = '/log4J/logging'

**Comment by jeffwils** [comment]
Should be

/spring-security-saml/saml/SSO/alias/{your alias}

Thank you also for the redirection info.  It is obviously incorrect.  I had that in there for testing.  I will add a config property to set the failure URL (and reset the default to authfail.

**Comment by HybridProgrammer** [comment]
I used /spring-security-saml/saml/SSO instead. 

I had problems using the alias it kept failing to find the alias in SAMLContextProviderImpl.java#populateLocalEntityId()
`// Populate entityId
            entityId = metadata.getEntityIdForAlias(localAlias);

            if (entityId == null) {
                throw new MetadataProviderException("No local entity found for alias " + localAlias + ", verify your configuration.");
            } else {
                logger.debug("Using SP {} specified in request with alias {}", entityId, localAlias);
            }`

entityId always returned null

without the alias SAMLContextProviderImpl.java#populateLocalEntityId() returns the default sp which is configured in application.groovy:
`grails.plugin.springsecurity.saml.metadata.sp.defaults.entityId = 'https://mysp.example.com'`

**Comment by parizpe1** [comment]
I also had problems using the alias, however the springsecurity extension is wired so that you can use:
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://grails.sp.example.com/saml/SSO" index="0" isDefault="true"/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:PAOS" Location="https://grails.sp.example.com/saml/SSO" index="1"/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://grails.sp.example.com/saml/SSO" index="2"/>

**Comment by irstevenson** [comment]
Are people still having issue with this? (If not, I plan to close.)

I personally have seen the alias endpoint work fine, but maybe I'm missing something.
